Correction map implemented too
HEPCloud/decisionengine_modules pull request #324
Opened 2021-04-08 20:37 UTC by hyunwoo18

2021-04-08 20:53 UTC, StevenCTimm approved these changes
I recommend acceptance of this pull request but would appreciate at least one other developer weighing in.  It has been tested on a real machine and real factory entries
and performs as needed.

2021-04-08 20:53 UTC, StevenCTimm commented on glideinwms/sources/factory_entries.py
> +                if correction_map is not None:
Tested this code in-situ on hepcsvc03 and it worked as scheduled.  I leave the task of determining code acceptability to others but functionally it is just what I requested and needed.

2021-04-08 21:07 UTC, hyunwoo18 commented
What is the next step?

2021-04-08 21:10 UTC, hyunwoo18 commented
<img width="912" alt="Screen Shot 2021-04-08 at 4 08 55 PM" src="https://user-images.githubusercontent.com/6930679/114096802-d4e7d400-9884-11eb-92b2-1384463d0f52.png">
Can I click on this "Merge pull request"? Or can only Marco do it?

2021-04-08 21:15 UTC, StevenCTimm commented
I would like to see at least one other developer double check the code.. I believe anyone with write access can 
hit "merge pull request" but would like Marco's ok first.

2021-04-12 14:03 UTC, jcpunk requested changes

2021-04-12 20:13 UTC, hyunwoo18 commented on glideinwms/sources/factory_entries.py
> +                                eachDict[key] = value
Marco, Steve and I talked about your point and agreed that I would open a new ticket (https://github.com/HEPCloud/decisionengine_modules/issues/325) for adding unit tests (not just in this file but also other related files too),
as I do not have time to work on this and Steve seems to need to this correction map logic right away.

2021-04-13 20:33 UTC, mambelli commented on glideinwms/sources/factory_entries.py
> +                                eachDict[key] = value
I know it is not a good practice but this time we'll address the test in a separate ticket, #325

2021-04-13 20:35 UTC, mambelli approved these changes

2021-04-13 20:36 UTC, merged

2021-04-13 20:36 UTC, mambelli commented
Forced merge. Unit test will be added in separate ticket #325